available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT es un modelo ampliamente conocido. Es <b>rápido</b> y <b>económico</b>. Ideal para tareas cotidianas. Si hay algunas tareas que no puede manejar, prueba con el modelo <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT es un modelo muy conocido. Es <b>rápido</b> y <b>económico</b>. Ideal para tareas cotidianas. Si hay algunas tareas que no puede manejar, prueba con el modelo <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.005
    price_per_1000_output_tokens: 0.006

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 es el modelo más <b>inteligente</b> y avanzado del mundo. Sin embargo, es más lento y no tan rentable en términos de costo como ChatGPT. Es la mejor opción para tareas intelectuales más <b>complejas</b>.

    price_per_1000_input_tokens: 0.04
    price_per_1000_output_tokens: 0.08

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 es un modelo heredado. En realidad, <b>no hay razón para usarlo</b>, ya que es más costoso y más lento que ChatGPT, pero prácticamente igual de inteligente.

    price_per_1000_input_tokens: 0.04
    price_per_1000_output_tokens: 0.04

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.008